### ISSUE TITLE
How can I run this on basic html or php file?

### ISSUE THREAD

**Issue by nikolayganovski1** [funkyremi/vtt-live-edit#7]
How can I run this on basic html or php file? 
where is the javascript file/functions ?

EDIT This is what I needed( JQ implementation):
$.each(myPlayer.textTracks_.tracks_ , function() {
          $.each(this.cues_, function() {
            this.startTime -= 2.5;
            this.endTime -= 2.5;
          });
        });
Thanks

**Comment by funkyremi** [comment]
You can use the file `index.js` which contain all the functions.
